/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        primary: '#0058BC',
        primary_container: '#0070EB',
        on_primary: '#FFFFFF',
        on_primary_container: '#FEFCFF',
        secondary: '#405E96',
        secondary_container: '#A1BEFD',
        on_secondary: '#FFFFFF',
        surface: '#F9F9FB',
        surface_container: '#EEEEEf',
        surface_container_low: '#F3F3F5',
        surface_container_lowest: '#FFFFFF',
        surface_container_high: '#E8E8EA',
        surface_container_highest: '#E2E2E4',
        on_surface: '#1A1C1D',
        on_surface_variant: '#414755',
        outline: '#717786',
        outline_variant: '#C1C6D7',
        error: '#BA1A1A',
      },
      fontFamily: {
        sans: ['Inter', 'system-ui', 'sans-serif'],
        mono: ['JetBrains Mono', 'monospace'],
      },
      fontSize: {
        'display-lg': ['3.5rem', { lineHeight: '1.1', letterSpacing: '-0.02em' }],
        'display-md': ['2.75rem', { lineHeight: '1.2', letterSpacing: '-0.02em' }],
        'title-lg': ['1.375rem', { lineHeight: '1.4' }],
        'title-md': ['1.125rem', { lineHeight: '1.5' }],
        'body-lg': ['1rem', { lineHeight: '1.6', letterSpacing: '0.01em' }],
        'body-sm': ['0.875rem', { lineHeight: '1.6', letterSpacing: '0.01em' }],
        'label-sm': ['0.6875rem', { lineHeight: '1.5', letterSpacing: '0.01em' }],
      },
      spacing: {
        'spacing-1': '0.25rem',
        'spacing-2': '0.5rem',
        'spacing-3': '0.75rem',
        'spacing-4': '1rem',
        'spacing-6': '1.5rem',
        'spacing-8': '2rem',
        'spacing-12': '3rem',
        'spacing-16': '4rem',
      },
      borderRadius: {
        'rounded-sm': '8px',
        'rounded-md': '12px',
        'rounded-lg': '16px',
        'rounded-xl': '24px',
      },
      boxShadow: {
        'env': '0 12px 40px rgba(26, 28, 29, 0.08)',
        'env-sm': '0 4px 16px rgba(26, 28, 29, 0.06)',
      },
    },
  },
  plugins: [],
}
